'use strict';
const assert=require('assert'),fs=require('fs');
const app=require('../server');
async function run(){
  assert.deepStrictEqual(app.assignments('example.com=s1|s2;example.net=google'),{'example.com':['s1','s2'],'example.net':['google']});
  process.env.MONITORED_DOMAINS='example.com,example.net';
  process.env.DKIM_SELECTORS='example.com=s1|s2;example.net=google';
  process.env.TLS_ENDPOINTS='example.com=mta-sts.example.com:443|mail.example.com:465';
  process.env.OPENSEARCH_PASSWORD='test-only';
  const config=app.envConfig();
  assert.strictEqual(config.domains.length,2);
  assert.deepStrictEqual(config.domains[0].dkim_selectors,['s1','s2']);
  assert.deepStrictEqual(config.domains[0].tls_endpoints,[{host:'mta-sts.example.com',port:443},{host:'mail.example.com',port:465}]);
  const settings=app.normalizeSettings({monitored_domains:['Example.com'],dkim_selectors:{'example.com':['s1','s2']},tls_endpoints:{'example.com':[{host:'mail.example.com',port:465}]},report_days:14,refresh_minutes:30,request_timeout_ms:5000,opensearch_enabled:false});
  assert.deepStrictEqual(settings.monitored_domains,['example.com']);
  assert.strictEqual(settings.opensearch_enabled,false);
  assert.strictEqual(app.settingsConfig(settings).domains[0].report_days,14);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['not a domain']}),/Invalid monitored domain/);
  assert.strictEqual(app.mxMatch('mx1.example.com','*.example.com'),true);
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}},'source_ip_address.keyword':{keyword:{aggregatable:true}}}),'source_ip_address.keyword');
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}}}),null);
  process.env.DEMO_MODE='true';const status=await app.refresh();assert.strictEqual(status.domains.length,1);assert.ok(status.summary.critical>0);assert.strictEqual(status.version,require('../package.json').version);
  const page=fs.readFileSync('public/index.html','utf8'),client=fs.readFileSync('public/app.js','utf8'),icon=fs.readFileSync('public/mailposture.svg','utf8');
  assert.match(page,/MailPosture/);
  assert.match(page,/id="dashboard-view"/);
  assert.match(page,/id="settings-view"/);
  assert.match(page,/id="help-view"/);
  assert.match(page,/id="domain-dialog"/);
  assert.match(page,/name="theme" value="system"/);
  assert.match(page,/aria-label="Settings"/);
  assert.match(page,/id="version"/);
  assert.match(client,/card-context/);
  assert.match(client,/renderDashboard/);
  assert.match(client,/renderSettingsDomains/);
  assert.match(icon,/<svg/);
  assert.match(icon,/check mark/i);
  console.log('All MailPosture checks passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
