'use strict';
const assert=require('assert'),fs=require('fs');
const app=require('../server');
async function run(){
  assert.deepStrictEqual(app.assignments('example.com=s1|s2;example.net=google'),{'example.com':['s1','s2'],'example.net':['google']});
  process.env.MONITORED_DOMAINS='example.com,example.net';
  process.env.DKIM_SELECTORS='example.com=s1|s2;example.net=google';
  process.env.TLS_ENDPOINTS='example.com=mta-sts.example.com:443|mail.example.com:465';
  process.env.OPENSEARCH_PASSWORD='test-only';
  const config=app.envConfig();
  assert.strictEqual(config.domains.length,2);
  assert.deepStrictEqual(config.domains[0].dkim_selectors,['s1','s2']);
  assert.deepStrictEqual(config.domains[0].tls_endpoints,[{host:'mta-sts.example.com',port:443},{host:'mail.example.com',port:465}]);
  const settings=app.normalizeSettings({monitored_domains:['Example.com'],dkim_selectors:{'example.com':['s1','s2']},tls_endpoints:{'example.com':[{host:'mail.example.com',port:465}]},report_days:14,refresh_minutes:30,request_timeout_ms:5000,report_source:'standalone',opensearch_url:'http://parsedmarc-opensearch:9200',mailbox:{enabled:true,host:'imap.example.com',port:993,username:'reports@example.com',reports_folder:'INBOX',archive_folder:'Archive'},snapshots:{enabled:true,cron:'0 2 * * *',delete_cron:'30 2 * * *',timezone:'UTC',retention_days:30,min_count:7,max_count:60}});
  assert.deepStrictEqual(settings.monitored_domains,['example.com']);
  assert.strictEqual(settings.opensearch_enabled,true);
  assert.strictEqual(settings.report_source,'standalone');
  assert.strictEqual(settings.schema_version,3);
  assert.strictEqual(settings.mailbox.archive_folder,'Archive');
  assert.strictEqual(settings.parsedmarc.general.save_smtp_tls,true);
  assert.strictEqual(settings.parsedmarc.mailbox.delete_smtp_tls,false);
  assert.strictEqual(settings.parsedmarc.opensearch.number_of_replicas,0);
  assert.strictEqual(app.normalizeSettings({parsedmarc:{mailbox:{batch_size:0}}}).parsedmarc.mailbox.batch_size,0);
  assert.strictEqual(settings.snapshots.cron,'0 2 * * *');
  process.env.OPENSEARCH_VERIFY_TLS='true';
  assert.strictEqual(app.normalizeSettings({monitored_domains:['example.com']}).opensearch_verify_tls,true);
  delete process.env.OPENSEARCH_VERIFY_TLS;
  assert.strictEqual(app.settingsConfig(settings).domains[0].report_days,14);
  assert.throws(()=>app.normalizeSettings({monitored_domains:['not a domain']}),/Invalid monitored domain/);
  assert.throws(()=>app.normalizeSettings({snapshots:{cron:'not cron'}}),/five-field cron/);
  assert.strictEqual(app.validCron('0 2 * * *'),true);
  assert.strictEqual(app.validCron('0 2 * *'),false);
  assert.strictEqual(app.validCron('99 2 * * *'),false);
  process.env.OPENSEARCH_PASSWORD='open%search';
  const ini=app.parsedmarcIni(settings,{imap_password:'test%secret'});
  assert.match(ini,/reports_folder = INBOX/);
  assert.match(ini,/archive_folder = Archive/);
  assert.match(ini,/password = test%%secret/);
  assert.match(ini,/password = open%%search/);
  assert.match(ini,/save_smtp_tls = True/);
  assert.match(ini,/delete_smtp_tls = False/);
  assert.match(ini,/since = 1d/);
  assert.match(ini,/number_of_replicas = 0/);
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,ini).status,'healthy');
  assert.strictEqual(app.parsedmarcConfigurationStatus({...settings,mailbox:{...settings.mailbox,enabled:false}},'').status,'warning');
  assert.strictEqual(app.parsedmarcConfigurationStatus(settings,'[general]\n[imap]\n').status,'critical');
  assert.strictEqual(app.overallStatus([{status:'healthy'},{status:'warning'}]),'warning');
  assert.strictEqual(app.overallStatus([{status:'warning'},{status:'critical'}]),'critical');
  assert.ok(Array.isArray(app.diagnosticLog().events));
  assert.throws(()=>app.normalizeSettings({parsedmarc:{mailbox:{since:'yesterday'}}}),/number followed by/);
  const smtp=app.summarizeSmtpHits([{_source:{organization_name:'Sender',date_begin:'2026-09-01T00:00:00Z',policies:[{policy_domain:'example.com',successful_session_count:20,failed_session_count:2,failure_details:[{result_type:'validation-failure',failed_session_count:2}]}]}}],'example.com',7);
  assert.strictEqual(smtp.successful,20);
  assert.strictEqual(smtp.failed,2);
  assert.strictEqual(smtp.failure_types[0].type,'validation-failure');
  assert.strictEqual(app.mxMatch('mx1.example.com','*.example.com'),true);
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}},'source_ip_address.keyword':{keyword:{aggregatable:true}}}),'source_ip_address.keyword');
  assert.strictEqual(app.selectSourceField({source_ip_address:{text:{aggregatable:false}}}),null);
  process.env.DEMO_MODE='true';const status=await app.refresh();assert.strictEqual(status.domains.length,1);assert.ok(status.summary.critical>0);assert.strictEqual(status.version,require('../package.json').version);
  assert.strictEqual(require('../package.json').version,'0.7.0');
  const page=fs.readFileSync('public/index.html','utf8'),client=fs.readFileSync('public/app.js','utf8'),styles=fs.readFileSync('public/settings.css','utf8'),icon=fs.readFileSync('public/mailposture.svg','utf8'),standalone=fs.readFileSync('compose.standalone.yml','utf8');
  assert.match(page,/MailPosture/);
  assert.match(page,/id="dashboard-view"/);
  assert.match(page,/id="settings-view"/);
  assert.match(page,/id="system-status-view"/);
  assert.match(page,/id="system-log"/);
  assert.match(page,/id="log-service"/);
  assert.match(page,/v0\.7\.0/);
  assert.match(page,/href="\/status"/);
  assert.match(page,/dashboard-icon/);
  assert.match(page,/monitored-domains-icon/);
  assert.match(page,/system-status-icon/);
  assert.match(page,/run-checks-icon/);
  assert.match(page,/settings-icon/);
  assert.match(page,/id="organization-reports"/);
  assert.match(page,/id="domain-reports"/);
  assert.match(page,/id="report-source"/);
  assert.match(page,/id="mailbox-enabled"/);
  assert.match(page,/id="snapshots-enabled"/);
  assert.match(page,/role="tablist"/);
  assert.match(page,/data-settings-tab="parsedmarc"/);
  assert.match(page,/domains-icon/);
  assert.match(page,/appearance-icon/);
  assert.match(page,/opensearch-icon/);
  assert.match(page,/parsedmarc-icon/);
  assert.match(page,/id="pm-delete-smtp-tls"/);
  assert.match(page,/Archive\/SMTP-TLS/);
  assert.match(page,/id="help-view"/);
  assert.match(page,/id="domain-dialog"/);
  assert.match(page,/name="theme" value="system"/);
  assert.match(page,/aria-label="Settings"/);
  assert.match(page,/id="version"/);
  assert.match(client,/card-context/);
  assert.match(client,/renderDashboard/);
  assert.match(client,/renderSettingsDomains/);
  assert.match(client,/organizationReports/);
  assert.match(client,/reportingOrganizationsCard/);
  assert.match(client,/DMARC failure \(RUF\) reports/);
  assert.match(client,/api\/system-logs/);
  assert.match(client,/api\/bimi-logo/);
  assert.match(client,/certificate-days/);
  assert.match(client,/issue-status/);
  assert.match(client,/data-report-target/);
  assert.match(client,/selectSettingsTab/);
  assert.ok(fs.existsSync('compose.standalone.yml'));
  assert.match(standalone,/ghcr\.io\/domainaware\/parsedmarc/);
  assert.match(standalone,/MAILPOSTURE_SETTINGS_PATH/);
  assert.match(standalone,/OPENSEARCH_DATA_PATH/);
  assert.match(standalone,/OPENSEARCH_SNAPSHOT_PATH/);
  assert.match(standalone,/type: bind/);
  assert.match(standalone,/target: \/etc\/parsedmarc\n\s+read_only: true/);
  assert.doesNotMatch(standalone,/target: \/etc\/parsedmarc:ro/);
  assert.match(standalone,/reloading parsedmarc/);
  assert.match(standalone,/parsedmarc_status/);
  assert.match(standalone,/write_status running/);
  assert.match(styles,/#0c71c3/i);
  assert.match(styles,/monitored-domains\.svg/);
  assert.match(styles,/appearance\.svg/);
  assert.match(styles,/opensearch\.svg/);
  assert.match(styles,/parsedmarc\.svg/);
  assert.match(styles,/dashboard\.svg/);
  assert.match(styles,/run-checks\.svg/);
  assert.match(styles,/settings\.svg/);
  assert.match(styles,/status\.svg/);
  assert.match(styles,/system-status\.svg/);
  assert.match(styles,/flex-direction:column-reverse/);
  assert.match(styles,/system-warning \.system-status-icon\{color:var\(--review-text\)\}/);
  assert.match(styles,/\.system-log/);
  assert.match(styles,/--review:#ffd60a/i);
  assert.match(icon,/<svg/);
  assert.match(icon,/check mark/i);
  assert.match(icon,/#0C71C3/);
  for(const iconFile of ['appearance.svg','dashboard.svg','monitored-domains.svg','opensearch.svg','parsedmarc.svg','run-checks.svg','settings.svg','status.svg','system-status.svg']) assert.ok(fs.existsSync(`public/${iconFile}`));
  console.log('All MailPosture checks passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
